### ISSUE TITLE
Should add warning messages at Readme.md 

### ISSUE THREAD

**Issue by sujunmin** [NetSPI/PowerUpSQL#12]
Last week I used this tool to test my sql servers, and then I got the mail from antivirus system administrators that I used "HackTool" at that time, It would violate the policies for my organization.

I used [VirusTotal](https://www.virustotal.com/en/file/19bebf4445af8b45e91352d334cb75e9586d95d8fa880f028ce3f2fcc6d20902/analysis/1494509241/) to scan this project files, some antivirus software said there is HackTool or Trojan.

So I think it should be added some warning messages at Readme.md for users who had antivirus softwares and need to keep the organization security policies.

**Comment by nullbind** [comment]
Thank you for the heads up. I'm sorry to hear that. I didn't know PowerUpSQL was getting flagged by AV.  Technically it's an auditing tool, not a "HackTool" or "Trojan".  However, I guess any software can be a HackTool if you choose to use it maliciously.   I'll think about integrating some obfuscation in the next release.  

Thanks again!
