### ISSUE TITLE
Invoke-SQLImpersonateServiceCmd missing

### ISSUE THREAD

**Issue by CaledoniaProject** [NetSPI/PowerUpSQL#14]
I can't find `Invoke-SQLImpersonateServiceCmd` in this repository, only a description in the `.psd` file, was it removed?

**Comment by nullbind** [comment]
As of version 1.82.95,  it is in PowerUpSQL.ps1 on line 17934.
https://github.com/NetSPI/PowerUpSQL/blob/master/PowerUpSQL.ps1#L17934

Hopefully that helps, but let me know if you continue to have any issues.

**Comment by CaledoniaProject** [comment]
Thanks, looks like a bug of github
