### ISSUE TITLE
 Get-SQLInstanceDomain misses named instances

### ISSUE THREAD

**Issue by dimpol** [NetSPI/PowerUpSQL#15]
On my lab domain I have added a MSSQLSERVER machine with the default settings. (no named instance)
Then, I added 2 named instances on the same machine.

 Get-SQLInstanceDomain run from another domain joined machine only identifies the first one and misses the two named instances that I added later.

Get-SQLInstanceLocal run on the MSSQLSERVER identifies all instances correctly, as expected.

Any clues what is going wrong?

**Comment by dimpol** [comment]
Had to manually set SPNs of course. I'm dumb.
By the way is it possible to add multiple SPNs under the same domain account?

**Comment by nullbind** [comment]
Im pretty sure you can as long as they are unique
