### ISSUE TITLE
ASCII disasters

### ISSUE THREAD

**Issue by peewpw** [NetSPI/PowerUpSQL#19]
There are some comments that seem to have had a quote blow up... I noticed when trying to import into Empire; it doesn't deal with non-ascii characters.

![not-so-ascii](https://user-images.githubusercontent.com/26287488/38343676-4a7e2aa6-3853-11e8-852d-c92e29ae971b.png)

**Comment by nullbind** [comment]
Hrm, well, that was unexpected.  I'll take a look and hit you back.

**Comment by nullbind** [comment]
Hey @peewpw  

It looks like I made a few copy and paste errors. :P  I think I've fixed all of the instances so I'm going to close out the ticket, but let me know if you have any other issues.

Thanks again for the heads up,

Scott
