### ISSUE TITLE
This module should be added to Empire Project's

### ISSUE THREAD

**Issue by bursaiskender** [NetSPI/PowerUpSQL#21]
This module is FANTASTIC. That's why you definitely add to https://github.com/EmpireProject/Empire.

**Comment by nullbind** [comment]
Hi @bursaiskender 

Thanks! I'm glad it was useful.  :)

Below are links to a few SQL Server Empire modules that @0xbadjuju created, but let me know if there is other functionality you would like to see ported over.
- https://github.com/EmpireProject/Empire/blob/05e6149a86b4d18ffa1422b221d1b347d7225676/lib/modules/powershell/recon/get_sql_server_login_default_pw.py
- https://github.com/EmpireProject/Empire/blob/05e6149a86b4d18ffa1422b221d1b347d7225676/lib/modules/powershell/situational_awareness/network/get_sql_server_info.py
- https://github.com/EmpireProject/Empire/blob/a5b100b2d8f413dd849c5773dea6d82ad1172a64/lib/modules/powershell/collection/get_sql_column_sample_data.py
- https://github.com/EmpireProject/Empire/blob/05e6149a86b4d18ffa1422b221d1b347d7225676/lib/modules/powershell/situational_awareness/network/get_sql_instance_domain.py
- https://github.com/EmpireProject/Empire/blob/05e6149a86b4d18ffa1422b221d1b347d7225676/lib/modules/powershell/collection/get_sql_query.py
