### ISSUE TITLE
Cheatsheet: "Invoke-SQLAuditWeakPw" command not found

### ISSUE THREAD

**Issue by ClementNotin** [NetSPI/PowerUpSQL#26]
In the [cheatsheet](https://github.com/NetSPI/PowerUpSQL/wiki/PowerUpSQL-Cheat-Sheet) there are two references to the `Invoke-SQLAuditWeakPw ` command but it's missing from the module (I'm using the current master version).
It looks like the command is instead: `Invoke-SQLAuditWeakLoginPw`

**Comment by nullbind** [comment]
Hi @ClementNotin,

Another good catch.  I've updated the wiki to reflect the changes. `Invoke-SQLAuditWeakPw`  has been replaced with `Invoke-SQLAuditWeakLoginPw`

Thanks for all the help,

Scott
