### ISSUE TITLE
Cheatsheet: small typo in "Execute arbitrary query"

### ISSUE THREAD

**Issue by ClementNotin** [NetSPI/PowerUpSQL#27]
In the [cheatsheet](https://github.com/NetSPI/PowerUpSQL/wiki/PowerUpSQL-Cheat-Sheet) the "Execute arbitrary query" entry is missing a '-' before the "Query" parameter name.
Currently we get a "No query provided" error.

**Comment by nullbind** [comment]
Hi @ClementNotin ,

I updated the wiki cheatsheet to include the "-".  Was that the primary issue, or were you having issues when you added the full "-Query" as well?

Thanks,

Scott

**Comment by ClementNotin** [comment]
You're welcome :)
Everything went fine after adding the "-". The query is correct!
Thanks
