### ISSUE TITLE
Standardize Cmdlet Verbs

### ISSUE THREAD

**Issue by aph3rson** [NetSPI/PowerUpSQL#30]
Per [Microsoft's documentation](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands), specific verbs are to be used for Powershell cmdlets, in order to ensure some consistency between third-party modules/official functionality. This is echoed in the warning presented when importing PowerUpSQL:
![image](https://user-images.githubusercontent.com/838916/44745874-87047000-aace-11e8-9b4c-881c8c01dcf5.png)

PowerUpSQL uses `Create` as a verb for these cmdlets:  
- `Create-SQLFileXpDll`
- `Create-SQLFileCLRDll`
- (internal function) `Create-ProcessWithToken`

To fix this, these cmdlets/functions should be refactored to use the `New` verb, which is recommended for use in instances when a new record/object is being created.

**Comment by aph3rson** [comment]
I'd be happy to submit a PR, if preferred.

**Comment by nullbind** [comment]
Hey @aph3rson,

Thanks for the request!  It would be nice to make things a little cleaner.  Let me take a see what that might impact and I will get back to you next week.

Thanks again,

Scott

**Comment by nullbind** [comment]
I decided to leave the verbs as is.  Thanks again for the thought though.

**Comment by aph3rson** [comment]
> I decided to leave the verbs as is. Thanks again for the thought though.

@nullbind if that's the case, could the documentation be updated to call out the expected warning on import?  
It's not documented anywhere, so folks using it can get confused and think the install was unsuccessful.
