### ISSUE TITLE
What does this message mean?

### ISSUE THREAD

**Issue by dsolstad** [NetSPI/PowerUpSQL#41]
> Invoke-SQLImpersonateService -Verbose -Instance MSSQLSvc/x
VERBOSE: MSSQLSvc/x: user has local admin privileges.
VERBOSE: MSSQLSvc/x: Impersonating SQL Server process:
VERBOSE: MSSQLSvc/x: No process running for provided instance...

Does this mean that it think that there are no SQL instances on that server?

**Comment by nullbind** [comment]
Yeah, it identifies the sql server instances by their associated windows services, but sometimes the services are not running.
