### ISSUE TITLE
Is there a way I can use PowerUpSQL in this scenario?

### ISSUE THREAD

**Issue by dsolstad** [NetSPI/PowerUpSQL#43]
I am directly connected to a VLAN where I found a MSSQL server. Is there a way I can use PowerUpSQL to audit the server? None of the discovery commands are finding it. 
There are no domain controllers and I am basically just plugged in with a Kali machine to the network. Though I have a valid set of AD credentials if needed.

**Comment by nullbind** [comment]
I have not run it on kali, but if you have the instance or ip+port information for the sql server you should be able to connect with valid credits using powerupsql and execute the audit function.  Also, you she be able to use the dictionary and weak password functions.

Command examples can be found at https://github.com/NetSPI/PowerUpSQL/wiki/PowerUpSQL-Cheat-Sheet
