### ISSUE TITLE
No valid module file was found in any module directory

### ISSUE THREAD

**Issue by ronnieflip** [NetSPI/PowerUpSQL#49]
What am I doing wrong. Been at the for two days.

```
PS > Import-Module PowerUpSQL.psd1
ERROR: Import-Module : The specified module 'PowerUpSQL.psd1' was not loaded because no valid module file was found in any mod
ERROR: ule directory.
ERROR:
ERROR: At line:1 char:14
ERROR: + Import-Module <<<<  PowerUpSQL.psd1
ERROR:     + CategoryInfo          : ResourceUnavailable: (PowerUpSQL.psd1:String) [Import-Module], FileNotFoundException
ERROR:     + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by nullbind** [comment]
From the error it looks like powerupsql.psd1 is not in the directory you’re executing the command from.  Have the powerupsql files already been downloaded to that directory?  

If not, here are a few other loading options. https://github.com/NetSPI/PowerUpSQL/wiki/Setting-Up-PowerUpSQL

Let me know if that helps,

Scott

**Comment by ronnieflip** [comment]
> From the error it looks like powerupsql.psd1 is not in the directory you’re executing the command from. Have the powerupsql files already been downloaded to that directory?
> 
> If not, here are a few other loading options. https://github.com/NetSPI/PowerUpSQL/wiki/Setting-Up-PowerUpSQL
> 
> Let me know if that helps,
> 
> Scott

It was in the right folder. However I got it working when I pointed to the full path. 

**This was encountered when using the metasploit powershell module**

**Comment by nullbind** [comment]
Thanks for the follow up and sharing your solution.  I’m sure other people will run into the same issue.
