### ISSUE TITLE
CONNECTION FAILED and Not Accessible Status while using PowerupSQL

### ISSUE THREAD

**Issue by gangesh11** [NetSPI/PowerUpSQL#60]
Hello – I am not able to connect some of the MS SQL instances using PowerUpSQL script, however, I can connect and verify the script for another SQL instance using my ads credentials along with standard ads account. The status shows “**Not Accessible**”..I can ping the SQL instances and also can perform UDP scan using PowerupSQL.My ads credentials are added in SQL instance, could you please help me to understand what could be the issue, What the **Not Accessible**  Below is the error message– thanks
**While using my ADS ID**
Error: Exception calling “Open” with “0” argument(s): “Connection Timeout Expired. The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement. This could be because the pre-login handshake failed or the server was unable to respond back in time. The duration spent while attempting to connect to this server was – [Pre-Login] initialization=767; handshake=232; ”
**While using my ADS service account id**
VERBOSE: Error: Exception calling “Open” with “0” argument(s): “Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with ‘kinit’ and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.

ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error – An unsupported mechanism was requested (unknown mech-code 0 for mech unknown)

**Comment by nullbind** [comment]
I have not run into either of those errors, and unfortunately don't have any words of wisdom.  However, to authenticate as an alternative domain user use `run as`.  Here is a cheat sheet.  Hopefully it helps.

https://github.com/NetSPI/PowerUpSQL/wiki/PowerUpSQL-Cheat-Sheet
