### ISSUE TITLE
Get-SQLServerPasswordHash: capitalize hash

### ISSUE THREAD

**Issue by cnotin** [NetSPI/PowerUpSQL#64]
The hashs from Get-SQLServerPasswordHash aren't accepted directly by John The Ripper. The issue is that the hexadecimal letters aren't capitalized.
So I suggest doing it :)
Except if you usually use a different tool which has different requirements?

**Comment by kfosaaen** [comment]
[This commit ](https://github.com/NetSPI/PowerUpSQL/commit/0f7b58c0244b990d1d21e5ba90293d0adc6b2d7c) should fix the case issue. Thanks for the suggestion!
